// some random words
export default [
    "Afghanistan",
	"Albania",
	"Algeria",
	"Bahrain",
	"Bangladesh",
	"Barbados",
	"Bouvet Island",
	"Brazil",
	"British Indian Ocean Territory (the)",
	"Brunei Darussalam",
	"Bulgaria",
	"Burkina Faso",
	"Burundi",
	"Cabo Verde",
	"Cambodia",
	"Cameroon",
	"Cyprus",
	"Czechia",
	"Côte d'Ivoire",
	"Denmark",
	"Fiji",
	"Finland",
	"Guernsey",
	"Guinea",
	"Guinea-Bissau",
	"Guyana",
	"Haiti",
	"Heard Island and McDonald Islands",
	"Holy See (the)",
	"Honduras",
    "India"
  ];
  